Repository NativeScript/nativescript-dev-webpack, pull requests merged in 2019-04, with the labels that each got.

#843 fix: support platform specific files that are not directly imported anywhere in the app
  index.js
  package.json
  plugins/NativeScriptAngularCompilerPlugin.ts
  templates/webpack.angular.js
  templates/webpack.config.spec.ts
  templates/webpack.javascript.js
  templates/webpack.typescript.js
  templates/webpack.vue.js
Labels: cla: yes, new PR, review

#845 chore: fix liveSync of html files in Angular apps
  plugins/NativeScriptAngularCompilerPlugin.ts
Labels: angular, bug, new PR, review

#847 fix: update the css loader in order to fix a bug with leading dashes in css classes
  demo/AngularApp/webpack.config.js
  demo/JavaScriptApp/webpack.config.js
  demo/TypeScriptApp/webpack.config.js
  package.json
  templates/webpack.angular.js
  templates/webpack.javascript.js
  templates/webpack.typescript.js
  templates/webpack.vue.js
Labels: cla: yes, new PR, review

#848 fix: respect ts files on `test` command
  unit-testing-config-loader.js
Labels: cla: yes, new PR, review

#850 chore: merge release into master
  CHANGELOG.md
  unit-testing-config-loader.js
Labels: new PR, review

#819 fix: sourceMap not generated with Uglify
  templates/webpack.angular.js
  templates/webpack.javascript.js
  templates/webpack.typescript.js
  templates/webpack.vue.js
Labels: cla: yes, new PR, review, ♥ community PR

#851 fix: use correct slashes on windows on test command
  unit-testing-config-loader.js
Labels: cla: yes, new PR, review

#852 chore: merge release into master
  unit-testing-config-loader.js
Labels: new PR, review

#854 feat: support hidden source maps to map error stack traces from crash reports
  index.js
  templates/webpack.angular.js
  templates/webpack.config.spec.ts
  templates/webpack.javascript.js
  templates/webpack.typescript.js
  templates/webpack.vue.js
Labels: cla: yes, new PR, review

#859 fix: fix "ERROR in Must have a source file to refactor." error from ngCompilerPlugin on `test` command
  templates/webpack.angular.js
Labels: new PR, review

#860 chore: merge release into master
  templates/webpack.angular.js
Labels: cla: yes, new PR, review

#857 fix: typescript source maps are containing javascript code
  android-app-components-loader.js
  apply-css-loader.js
  bundle-config-loader.js
  css2json-loader.js
  markup-hot-loader.js
  script-hot-loader.js
  style-hot-loader.js
  templates/webpack.typescript.js
  xml-namespace-loader.js
Labels: new PR, review

#862 Merge release into master
  android-app-components-loader.js
  apply-css-loader.js
  bundle-config-loader.js
  css2json-loader.js
  markup-hot-loader.js
  script-hot-loader.js
  style-hot-loader.js
  templates/webpack.typescript.js
  xml-namespace-loader.js
Labels: cla: yes, new PR, review

#858 feat: replace UglifyJs with Terser
  demo/AngularApp/webpack.config.js
  demo/JavaScriptApp/webpack.config.js
  demo/TypeScriptApp/webpack.config.js
  dependencyManager.js
  package.json
  templates/webpack.angular.js
  templates/webpack.config.spec.ts
  templates/webpack.javascript.js
  templates/webpack.typescript.js
  templates/webpack.vue.js
Labels: cla: yes

#869 release: cut the 0.21.1 release
  CHANGELOG.md
  package.json
Labels: cla: yes, new PR, review

#870 fix: add support for executing unit tests for vue projects (#839)
  templates/webpack.vue.js
Labels: cla: yes, new PR, review

#871 release: cut the 0.21.2 release
  CHANGELOG.md
  package.json
Labels: cla: yes, new PR, review

#873 fix: ignore the Webpack runtime chunks when sending HMR updates
  lib/compiler.js
  lib/utils.js
  plugins/WatchStateLoggerPlugin.ts
Labels: cla: yes, new PR, review
