Repository NativeScript/nativescript-dev-webpack, pull requests merged in 2019-06, with the labels that each got.

#922 fix: handle entry points with custom output filename
  plugins/GenerateNativeScriptEntryPointsPlugin.js
  plugins/NativeScriptSnapshotPlugin/index.js
Labels: cla: yes

#919 fix: stop generating .d.ts on TS compilation
  templates/webpack.typescript.js
  templates/webpack.vue.js
Labels: bug, cla: yes

#924 fix: do not include hot updates when generating requires in entry files
  plugins/GenerateNativeScriptEntryPointsPlugin.js
Labels: cla: yes

#926 fix: handle types check in a child process
  templates/webpack.typescript.js
Labels: cla: yes

#928 chore: merge release into master
  CHANGELOG.md
  templates/webpack.typescript.js
  templates/webpack.vue.js
Labels: cla: yes

#930 release: cut the 0.24.1 release
  CHANGELOG.md
  package.json
Labels: cla: yes

#929 fix: handle file dependencies in non root entry modules
  plugins/GenerateNativeScriptEntryPointsPlugin.js
Labels: cla: yes

#931 fix: migrate demo apps to android x
  demo/AngularApp/app/activity.android.ts
  demo/AngularApp/app/application.d.ts
  demo/JavaScriptApp/app/activity.android.js
  demo/TypeScriptApp/app/activity.android.ts
  demo/TypeScriptApp/app/application.d.ts
  demo/TypeScriptApp/nsconfig.json
Labels: cla: yes

#933 chore: merge release into master
  CHANGELOG.md
Labels: cla: yes

#935 fix(ios): emit inspector_modules as a module
  demo/AngularApp/webpack.config.js
  demo/JavaScriptApp/webpack.config.js
  demo/TypeScriptApp/webpack.config.js
  templates/webpack.angular.js
  templates/webpack.javascript.js
  templates/webpack.typescript.js
  templates/webpack.vue.js
Labels: cla: yes

#936 fix: do not add inspector_modules entry when core modules are an external module
  templates/webpack.angular.js
  templates/webpack.config.spec.ts
  templates/webpack.javascript.js
  templates/webpack.typescript.js
  templates/webpack.vue.js
Labels: cla: yes

#882 feat: introduce webpack only workflow
  demo/AngularApp/package.json
  demo/AngularApp/webpack.config.js
  demo/JavaScriptApp/app/activity.android.js
  demo/JavaScriptApp/app/app.js
  demo/JavaScriptApp/app/main-page.android.js
  demo/JavaScriptApp/app/main-page.ios.js
  demo/JavaScriptApp/app/main-view-model.js
  demo/JavaScriptApp/package.json
  demo/JavaScriptApp/webpack.config.js
  demo/TypeScriptApp/app/activity.android.ts
  demo/TypeScriptApp/app/app.ts
  demo/TypeScriptApp/app/main-page.ios.ts
  demo/TypeScriptApp/app/main-view-model.ts
  demo/TypeScriptApp/package.json
  demo/TypeScriptApp/webpack.config.js
  lib/after-prepare.js
  lib/after-watch.js
  lib/before-cleanApp.js
  lib/before-prepareJS.js
  lib/before-preview-sync.js
  lib/before-shouldPrepare.js
  lib/before-watch.js
  lib/before-watchPatterns.js
  lib/compiler.js
  lib/utils.js
  package.json
  plugins/WatchStateLoggerPlugin.ts
  projectHelpers.js
  templates/webpack.angular.js
  templates/webpack.javascript.js
  templates/webpack.typescript.js
  templates/webpack.vue.js
Labels: cla: yes, new PR, review

#941 fix: follow the symlinks in JavaScript apps
  templates/webpack.javascript.js
Labels: cla: yes

#946 fix: fix hmr for platform specific files in linked plugins
  demo/JavaScriptApp/webpack.config.js
  demo/TypeScriptApp/webpack.config.js
  plugins/PlatformFSPlugin.ts
  templates/webpack.javascript.js
  templates/webpack.typescript.js
  templates/webpack.vue.js
Labels: cla: yes

#940 fix(xml-ns-loader): remove wrong register of xml
  xml-namespace-loader.js
Labels: cla: yes

#947 fix: do not show warning for format differences in templates
  projectFilesManager.js
Labels: cla: yes

#948 fix: don't throw an error from after-prepare hook when running legacy workflow with CLI <= v5.4.2 and nativescript-dev-webpack@next
  lib/after-prepare.js
Labels: cla: yes

#949 fix: inject app.css file from unit-test-runner on test command
  unit-testing-config-loader.js
Labels: cla: yes

#951 chore: bump version to 1.0.0
  package.json
Labels: cla: yes

#953 fix: hmr should work with uglify
  plugins/WatchStateLoggerPlugin.ts
Labels: bug, cla: yes

#954 refactor: fix deprecated APIs
  demo/AngularApp/app/activity.android.ts
  demo/AngularApp/app/main.ts
  demo/AngularApp/webpack.config.js
  demo/JavaScriptApp/app/activity.android.js
  demo/JavaScriptApp/app/app-root.xml
  demo/JavaScriptApp/app/app.js
  demo/TypeScriptApp/app/activity.android.ts
  demo/TypeScriptApp/app/app-root.xml
  demo/TypeScriptApp/app/app.ts
Labels: cla: yes

#955 fix: fix app.css file path on windows machines
  unit-testing-config-loader.js
Labels: cla: yes
