Repository NativeScript/nativescript-dev-webpack, pull requests merged in 2019-05, with the labels that each got.

#880 chore: merge release into master
  CHANGELOG.md
  lib/compiler.js
  lib/utils.js
  plugins/WatchStateLoggerPlugin.ts
Labels: new PR, review

#878 fix(hmr): run ts-loader in transpileOnly mode
  package.json
  templates/webpack.typescript.js
Labels: cla: yes

#886 chore: freeze fork-ts-checker-webpack-plugin
  package.json
Labels: cla: yes, new PR, review

#893 fix: clean up snpashot tool on download fail
  snapshot/android/snapshot-generator.js
  snapshot/android/utils.js
Labels: cla: yes, new PR, review

#888 chore: bump version
  package.json
Labels: cla: yes, new PR, review

#889 release: cut the 0.22.0 release
  CHANGELOG.md
Labels: cla: yes, new PR, review

#905 chore: merge release in master
  CHANGELOG.md
  snapshot/android/snapshot-generator.js
  snapshot/android/utils.js
Labels: cla: yes

#904 fix: import the workaroundResolve funciton based on the Angular version (it was moved from compiler_host to utils in Angular 8)
  dependencyManager.js
  package.json
  projectHelpers.js
  templates/webpack.angular.js
  transformers/ns-replace-bootstrap.spec.ts
  transformers/ns-replace-bootstrap.ts
  transformers/ns-replace-lazy-loader.spec.ts
  transformers/ns-replace-lazy-loader.ts
  transformers/ns-support-hmr-ng.spec.ts
  utils/transformers-utils.ts
Labels: cla: yes

#912 fix: bump version to 0.24.0
  package.json
Labels: cla: yes

#916 release: cut the 0.24.0 release
  CHANGELOG.md
Labels: cla: yes

#915 chore: bump version to 0.25.0
  package.json
Labels: cla: yes

#896 fix: unify the entry points handling and enable custom applications support in android
  demo/AngularApp/package.json
  demo/AngularApp/webpack.config.js
  demo/JavaScriptApp/webpack.config.js
  demo/TypeScriptApp/webpack.config.js
  dependencyManager.js
  plugins/GenerateBundleStarterPlugin.js
  plugins/GenerateNativeScriptEntryPointsPlugin.js
  plugins/NativeScriptSnapshotPlugin/index.js
  plugins/index.js
  templates/webpack.angular.js
  templates/webpack.config.spec.ts
  templates/webpack.javascript.js
  templates/webpack.typescript.js
  templates/webpack.vue.js
Labels: cla: yes, new PR, review
