Repository NativeScript/nativescript-dev-webpack, pull requests merged in 2019-02, with the labels that each got.

#771 fix: some packages are treated as externals when they shouldn't
  index.js
  index.spec.ts
  package.json
  templates/webpack.angular.js
  templates/webpack.config.spec.ts
  templates/webpack.javascript.js
  templates/webpack.typescript.js
  templates/webpack.vue.js
Labels: bug

#800 fix: add a typescript module resolution when searching for the main Angular module location
  templates/webpack.angular.js
  utils/ast-utils.ts
Labels: patch

#802 feat: allow angular resolver configuration via webpack.config
  host/resolver.ts
Labels: angular, patch

#801 chore: bump ng dependencies to match ns-angular
  package.json
Labels: angular, patch

#805 chore: bump ng dependencies version
  dependencyManager.js
Labels: angular, patch

#822 fix: fix "Cannot read property 'kill' of undefined" error
  lib/compiler.js
Labels: cla: yes

#824 fix(xml-namespace-loader) Fix obvious argument typo
  xml-namespace-loader.js
Labels: cla: yes
