Repository NativeScript/nativescript-dev-webpack, pull requests merged in 2019-03, with the labels that each got.

#783 refactor: skip copying of the native app resources on `tns preview`
  templates/webpack.angular.js
  templates/webpack.config.spec.ts
  templates/webpack.javascript.js
  templates/webpack.typescript.js
  templates/webpack.vue.js
Labels: cla: yes, review

#821 fix: show message for stopping webpack only when it has been started
  lib/after-watch.js
  lib/before-watch.js
  lib/compiler.js
Labels: cla: yes

#828 feat: Support Angular Ivy modules with AOT
  transformers/ns-replace-bootstrap.spec.ts
  transformers/ns-replace-bootstrap.ts
Labels: cla: yes, review

#831 release: cut the 0.20.3 release
  CHANGELOG.md
Labels: cla: yes, review

#833 chore: merge release in master
  CHANGELOG.md
  lib/after-watch.js
  lib/before-watch.js
  lib/compiler.js
  templates/webpack.angular.js
  templates/webpack.javascript.js
  templates/webpack.typescript.js
  templates/webpack.vue.js
Labels: review

#829 fix: execute bundle-config-loader only for the entry point of the application
  templates/webpack.angular.js
  templates/webpack.javascript.js
  templates/webpack.typescript.js
  templates/webpack.vue.js
Labels: cla: yes, review

#835 feat: Implement unit testing with bundle
  bundle-config-loader.js
  templates/webpack.angular.js
  templates/webpack.javascript.js
  templates/webpack.typescript.js
  templates/webpack.vue.js
  unit-testing-config-loader.js
Labels: cla: yes, review

#838 chore: entryPath check should work on Windows
  index.js
  index.spec.ts
  templates/webpack.angular.js
  templates/webpack.config.spec.ts
  templates/webpack.javascript.js
  templates/webpack.typescript.js
  templates/webpack.vue.js
Labels: bug, cla: yes, review

#836 fix: stop deleting chunks with compilation errors
  plugins/WatchStateLoggerPlugin.ts
Labels: cla: yes, review

#834 docs: update release schema
  CONTRIBUTING.md
  merge-guidance-schema.png
  release-contribution-guide-schema-webpack.png
Labels: cla: yes, review

#840 release: cut the 0.21.0 release
  CHANGELOG.md
Labels: review

#841 chore: bump version to 0.22.0
  package.json
Labels: cla: yes, review

#839 fix: add support for executing unit tests for vue projects
  templates/webpack.vue.js
Labels: cla: yes, review

#844 fix: respect files property from karma.config on `tns test android --bundle` command
  unit-testing-config-loader.js
Labels: cla: yes, new PR, review
