Repository NativeScript/nativescript-dev-webpack, pull requests merged in 2019-11, with the labels that each got.

#1092 chore: add phrases in pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cla: yes

#1091 fix: remove tns-core-modules dependency in order to allow @nativescrip/core migration
  css2json-loader.ts
  package.json
Labels: cla: yes

#1093 feat: stop using the proxy `tns-core-modules` package when the `@nativescript/core` is available
  index.js
  templates/webpack.angular.js
  templates/webpack.config.spec.ts
  templates/webpack.javascript.js
  templates/webpack.typescript.js
  templates/webpack.vue.js
Labels: cla: yes

#1100 chore: update demo applications
  demo/AngularApp/webpack.config.js
  demo/JavaScriptApp/app/app.android.css
  demo/JavaScriptApp/app/app.common.css
  demo/JavaScriptApp/app/app.ios.css
  demo/JavaScriptApp/webpack.config.js
  demo/TypeScriptApp/webpack.config.js
Labels: cla: yes

#1097 fix: bundle emitted on save without changes
  plugins/GenerateNativeScriptEntryPointsPlugin.js
Labels: bug, cla: yes, e2e test needed

#1099 fix: fix module import of local css files
  css2json-loader.spec.ts
  css2json-loader.ts
Labels: bug, cla: yes

#1077 feat: snapshot in Docker on macOS with Android runtime 6.3.0 or higher
  snapshot/android/project-snapshot-generator.js
  snapshot/android/snapshot-generator.js
Labels: cla: yes

#1102 fix: update worker loader in order to fix HMR
  package.json
Labels: cla: yes
